### ISSUE TITLE
Get Labels from *.lyr files to work.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#36] opened 2020-05-13 23:55 UTC
## The Problem
In Number 11 & 12 of #33, we bring up this problem:

> ## 10. Unit ID label missing

> I thought labels came over with UnitNum.lyr? This adds to map with right symbology, but the label customization are missing (just trying to show label for UnitID field number).
> https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/topo.xml#L11

![image](https://user-images.githubusercontent.com/9723905/81877576-ab261000-9542-11ea-8705-7e22a2acf351.png)

@philipbaileynar says this is a new feature. Just flagging it here.

**Comment by joewheaton** [comment] 2020-06-03 05:34
Confirming that this was not addressed in 1.1.0.

**Comment by philipbaileynar** [comment] 2020-06-03 15:50
Confirmed. This didn't make it in.

**Comment by joewheaton** [comment] 2020-09-18 18:09
@philipbaileynar can you give me an update on this one? It would be really helpful for a bunch of our RS projects.

**Comment by philipbaileynar** [comment] 2020-09-21 18:45
@joewheaton can you please test this feature using release 1.1.10

Probably easiest to test using a local layer file in your AppData symbology folder that has labels.

Please close this issue if it works. Post comment/error/behaviour if it does not.

**Comment by joewheaton** [comment] 2020-09-21 18:55
Actually, I turned them on in published version for Topo. It works... but other minor bug.

https://youtu.be/S35uLRtWzoE

[![](http://img.youtube.com/vi/S35uLRtWzoE/0.jpg)](http://www.youtube.com/watch?v=S35uLRtWzoE "")

**Comment by philipbaileynar** [comment] 2020-09-21 21:23
Closing this issue because labels are working. The outstanding issues raised by @joewheaton relate to inconsistencies in topo project channel unit ShapeFiles; specifically whether they have grain size attributes. I will review the outstanding issues and ensure that those problems are captured in the appropriate places.

**Closed by philipbaileynar** 2020-09-21 21:23 UTC
Labels: enhancement
