### ISSUE TITLE
Fix Topo Grain Size layer symbology

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#86] opened 2020-09-21 18:41 UTC
## The Problem
From end of #73 we need Fix symbology for Topo Grain Size layer files to work over entire expected range of values. I produced these initially off of an arbitrary topo survey that didn't span full range of values. As such, the symbology shows up empty in some surveys (more on low-end of grain sizes).

## Reproduction steps
See towards [end of video](https://youtu.be/lZT7h3ozUSA?t=428)
[![](http://img.youtube.com/vi/lZT7h3ozUSA/0.jpg)](http://www.youtube.com/watch?v=lZT7h3ozUSA "")

**Comment by philipbaileynar** [comment] 2021-02-16 18:56
This is a duplicate of #87

**Closed by philipbaileynar** 2021-02-16 18:56 UTC
Labels: :beetle: bug
